on: [pull_request]
name: build
jobs:
  build:
    name: build x86_64-unknown-none
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rust-src
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -Z build-std --target x86_64-unknown-none
